### PR TITLE
Support stdin and stdout

### PR DESCRIPTION
**Pull request by Jayshua**
Adds support for reading from stdin and writing to stdout.

Since the input/output arguments are optional now, I switched to using the `-i` flag to indicate the input file and the `-o` flag to indicate the output file. Parsing provided by `clap` which I added as a dependency.

Since that change isn't backwards-compatible, I incremented the major version number.

I also upgraded dependencies to their latest versions and relaxed the version requirements for `serde_cbor` and `serde-transcode` so they could upgrade to latest as well. It doesn't appear a specific patch version is required by the code for those two dependencies.

### CODE REVIEW

**Comment by Jayshua** [comment]
I realized that optional input/output files aren't incompatible with positional input/output parameters. So I added the positional parameters back in and swapped the version from "2.0.0" to "1.1.0" since the changes are now backwards-compatible.

**Comment by Timmmm** [comment]
Thanks! This looks great. I like the idea of supporting both flag and positional arguments but it is a bit confusing:

```
USAGE:
    json2cbor [OPTIONS] [ARGS]

ARGS:
    <INPUT>     Input file to read from. Reads from stdin if not present
    <OUTPUT>    Output file to read from. Reads from stdout if not present

OPTIONS:
    -h, --help               Print help information
    -i, --input <INPUT>      Input file to read from. Reads from stdin if not present
    -o, --output <OUTPUT>    Output file to write to. Writes to stdout if not present
    -V, --version            Print version information
```

No clue about what happens if you do both, or which takes priority etc. I think I prefer your earlier version that requires the flags. Feels like a normal interface. I don't think this has enough users to particularly care about breaking backwards compatibility!

What do you think?

**Comment by Jayshua** [comment]
I marked the positional and flag parameters as mutually exclusive, so if you use them together you get this message:

```
> json2cbor -i input.js input.js
error: The argument '--input <INPUT>' cannot be used with '<INPUT>'

USAGE:
    json2cbor --input <INPUT>

For more information try --help
```

------

I'm building a server using CBOR as an API protocol - using the tools to generate API requests and decode responses like this:

```sh
json2cbor input.json | websocat -b ws://127.0.0.1:3030/ws | cbor2json
```

Or like this to inspect the structure of a cbor message:

```sh
json2cbor input.json | xxd
```

Main reason I added positional parameters back in is because as soon as I added support for stdin/stdout I went back to working on my API server and kept trying to type `json2cbor input.json | xxd` to see the CBOR binary representation, or trying to run `cbor2json out.cbor` to see what a response looked like after generating it with `websocat -b ws://127.0.0.1:3030/ws > out.cbor`. It felt a bit annoying that I had to use -i for the obvious use-case. My immediate thought was "it's stupid that it doesn't support `json2cbor input.json` - it's obvious what I mean."

Here's what `xxd`'s help message looks like:

```
xxd [options] [infile [outfile]]
```

which is a bit clearer, so that's an option.

On the other hand I agree it's a bit weird to have two different ways to pass the two supported parameters. I propose we support only positional input files and only flag output files. That clarifies the auto-generated help message so we don't have to override it:

```
USAGE:
    json2cbor [OPTIONS] [INPUT_FILE]

ARGS:
    <INPUT_FILE>    Input file to read from. Reads from stdin if not present

OPTIONS:
    -h, --help               Print help information
    -o, --output <OUTPUT>    Output file to write to. Writes to stdout if not present
    -V, --version            Print version information
```

I think that keeps the clarity of the error message without loosing the ergonomics of `json2cbor input.js`. Your thoughts?

**Comment by Timmmm** [comment]
Yeah I like your last proposal. Let's do that!

**Comment by Jayshua** [comment]
@Timmmm Done!

**Comment by Timmmm** [comment]
Awesome, thanks! I'll upload a new version to crates.io tonight.

**Pull request merged**
